import TwitterNavbar from "@/components/twitterNavbar";
import "./globals.css";
import { Rubik } from "next/font/google";
import { NextAuthProvider } from "./providers";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <NextAuthProvider>
          {/* <TwitterNavbar /> */}
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
